name: bytes_data_builder
description: Builds a list of bytes, allowing bytes, fixed-width integers, floats and lists of bytes to be added at the end.
version: 0.1.4
author: Kurt Morris <kurt.morris.work@gmail.com>
homepage: https://github.com/kurtmorris/bytes_data_builder

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: '>=0.12.0 <0.13.0'
  collection: any
