name: bytes_data_builder
description: Builds a list of bytes, allowing bytes, integers(8, 16, 32 & 64 bit), floats and lists of bytes to be added at the end.
version: 0.1.3
author: Kurt Morris <kurt.morris.work@gmail.com>
homepage: https://pub.dartlang.org/packages/bytes_data_builder

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: '>=0.12.0 <0.13.0'
  collection: any
